/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package PilihData;

import java.awt.Dialog;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Doni Fitriansyah
 */
public class DataBuku extends javax.swing.JDialog {

    String kodeBuku;
    String judulBuku;
    String pengarang;
    String penerbit;
    String tahunTerbit;
    Integer bukuStok;

    DefaultTableModel model;
    Connection koneksi;
    Statement perintah;
    ResultSet rs;

    public String getKodeBuku() {
        return kodeBuku;
    }

    public String getJudulBuku() {
        return judulBuku;
    }

    public String getPengarang() {
        return pengarang;
    }

    public String getPenerbit() {
        return penerbit;
    }

    public String getTahunTerbit() {
        return tahunTerbit;
    }
    
    public Integer getStokBuku() {
        return bukuStok;
    }
    
    

    /**
     * Creates new form DataKategori
     */
    public DataBuku(Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        model = (DefaultTableModel) tblData.getModel();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost/sipustaka";
            String user = "root";
            String password = "";
            koneksi = DriverManager.getConnection(url, user, password);
            perintah = koneksi.createStatement();
        } catch (ClassNotFoundException e) {
            System.err.println("JDBC Driver tidak ditemukan");
        } catch (SQLException e) {
            System.err.println("Gagal koneksi atau menciptakan objek statement");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel1.setText("Pilih Data Buku");

        txtSearch.setText("Search");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 2, 10)); // NOI18N
        jLabel2.setText("*Silahkan klik buku yang tersedia didalam tabel");

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Buku", "Judul buku", "Pengarang", "Tahun Terbit", "Kategori", "Penerbit", "Stok", "ID Kategori", "ID Penerbit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.getTableHeader().setReorderingAllowed(false);
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        txtSearch.setText("");
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        String keyword = txtSearch.getText();

        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        model.setRowCount(0);
        try {
            String sql = "SELECT b.kode_buku, b.judul_buku, b.pengarang, b.tahun_terbit,"
                    + "k.nama_kategori, p.nama_penerbit, b.stok, b.kode_kategori, b.kode_penerbit "
                    + "FROM buku b "
                    + "INNER JOIN kategori k ON k.kode_kategori = b.kode_kategori "
                    + "INNER JOIN penerbit p ON p.kode_penerbit = b.kode_penerbit "
                    + "WHERE b.kode_buku LIKE ? OR b.judul_buku LIKE ? OR b.pengarang LIKE ? "
                    + "OR b.tahun_terbit LIKE ? OR k.nama_kategori LIKE ? OR LOWER(p.nama_penerbit) LIKE LOWER(?) "
                    + "OR b.stok LIKE ? OR b.kode_kategori LIKE ? OR b.kode_penerbit LIKE ? ORDER BY b.kode_buku ASC";
            try (PreparedStatement st = koneksi.prepareStatement(sql)) {
                st.setString(1, "%" + keyword + "%");
                st.setString(2, "%" + keyword + "%");
                st.setString(3, "%" + keyword + "%");
                st.setString(4, "%" + keyword + "%");
                st.setString(5, "%" + keyword + "%");
                st.setString(6, "%" + keyword + "%");
                st.setString(7, "%" + keyword + "%");
                st.setString(8, "%" + keyword + "%");
                st.setString(9, "%" + keyword + "%");
                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("kode_buku"),
                        rs.getString("judul_buku"),
                        rs.getString("pengarang"),
                        rs.getString("tahun_terbit"),
                        rs.getString("nama_kategori"),
                        rs.getString("nama_penerbit"),
                        rs.getString("stok"),
                        rs.getString("kode_kategori"),
                        rs.getString("kode_penerbit")
                    });
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtSearchKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_formWindowOpened

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        if (tblData.getSelectedRow() >= 0) {
            int stokBuku = Integer.parseInt(model.getValueAt(tblData.getSelectedRow(), 6).toString());
            if (stokBuku > 0) {
                kodeBuku = model.getValueAt(tblData.getSelectedRow(), 0).toString();
                judulBuku = model.getValueAt(tblData.getSelectedRow(), 1).toString();
                pengarang = model.getValueAt(tblData.getSelectedRow(), 2).toString();
                tahunTerbit = model.getValueAt(tblData.getSelectedRow(), 3).toString();
                penerbit = model.getValueAt(tblData.getSelectedRow(), 5).toString();
                bukuStok = Integer.parseInt(model.getValueAt(tblData.getSelectedRow(), 6).toString());
                ((DefaultTableModel) tblData.getModel()).fireTableDataChanged();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Stok buku habis.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public void tampilData() {
        try {
            rs = perintah.executeQuery(
                    "SELECT b.kode_buku, b.judul_buku, b.pengarang, b.tahun_terbit, "
                    + "k.kode_kategori, k.nama_kategori, "
                    + "p.kode_penerbit, p.nama_penerbit, "
                    + "b.stok "
                    + "FROM buku b "
                    + "INNER JOIN kategori k ON k.kode_kategori = b.kode_kategori "
                    + "INNER JOIN penerbit p ON p.kode_penerbit = b.kode_penerbit "
                    + "ORDER BY b.kode_buku ASC;"
            );
            model.setRowCount(0);
            model.fireTableDataChanged();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("kode_buku"),
                    rs.getString("judul_buku"),
                    rs.getString("pengarang"),
                    rs.getString("tahun_terbit"),
                    rs.getString("nama_kategori"),
                    rs.getString("nama_penerbit"),
                    rs.getString("stok"),
                    rs.getString("kode_kategori"),
                    rs.getString("kode_penerbit")
                });
            }
        } catch (SQLException e) {
            System.err.println("Query Error");
            e.printStackTrace();
        }
    }
}
