/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Menu;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Doni Fitriansyah
 */
public class KelolaDataAnggota extends javax.swing.JDialog {

    boolean modeSimpan;
    boolean dataDitemukan;
    boolean emailDitemukan;
    boolean teleponDitemukan;
    DefaultTableModel model;
    Connection koneksi;
    Statement perintah;
    ResultSet rs;

    /**
     * Creates new form KelolaDataAnggota
     */
    public KelolaDataAnggota(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) tblData.getModel();
        modeSimpan = true;
        dataDitemukan = false;
        emailDitemukan = false;
        teleponDitemukan = false;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost/sipustaka";
            String user = "root";
            String password = "";
            koneksi = DriverManager.getConnection(url, user, password);
            perintah = koneksi.createStatement();
        } catch (ClassNotFoundException e) {
            System.err.println("JDBC Driver tidak ditemukan");
        } catch (SQLException e) {
            System.err.println("Gagal koneksi atau menciptakan objek statement");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser2 = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        cbxJenisKelamin = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        btnBaru = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        dateChooser2.setForeground(new java.awt.Color(51, 51, 51));
        dateChooser2.setDateFormat("yyyy-MM-dd");
        dateChooser2.setTextRefernce(txtTanggal);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Anggota");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setText("Kelola Data Anggota");

        txtTelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTeleponKeyTyped(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        cbxJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
        cbxJenisKelamin.setSelectedIndex(-1);

        txtSearch.setText("Search");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Anggota ( NIM )", "Nama", "Email", "Telepon", "Jenis Kelamin", "Tanggal Bergabung"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jLabel2.setText("Kode Anggota ( NIM )");

        jLabel3.setText("Nama Anggota");

        jLabel4.setText("Email");

        jLabel5.setText("Telepon");

        jLabel6.setText("Jenis Kelamin");

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        jLabel7.setText("Tanggal Bergabung");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText(" \"Tekan tombol Enter untuk melanjutkan.\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNama)
                                        .addComponent(txtTelepon)
                                        .addComponent(cbxJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        dataDitemukan = cariData(txtID.getText());
        emailDitemukan = cariDataEmail(txtEmail.getText());
        teleponDitemukan = cariDataTelepon(txtTelepon.getText());
        if (txtNama.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan lengkapi data nama anggota!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            txtNama.requestFocus();
        } else if (txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan lengkapi data email!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            txtEmail.requestFocus();
        } else if (txtTelepon.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan lengkapi data telepon!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            txtTelepon.requestFocus();
        } else if (cbxJenisKelamin.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih jenis kelamin!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            cbxJenisKelamin.requestFocus();
        } else if (txtTanggal.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Silahkan lengkapi data tanggal bergabung!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            txtTanggal.requestFocus();
        } else {
            if (modeSimpan) {

                if (dataDitemukan) {
                    JOptionPane.showMessageDialog(this, "Data gagal ditambahkan, " + "karena kode anggota " + txtID.getText() + " telah ada di tabel", "Informasi", JOptionPane.ERROR_MESSAGE);
                } else if (emailDitemukan) {
                    JOptionPane.showMessageDialog(this, "Data gagal ditambahkan, " + "karena email " + txtEmail.getText() + " telah digunakan", "Informasi", JOptionPane.ERROR_MESSAGE);
                    return;
                } else if (teleponDitemukan) {
                    JOptionPane.showMessageDialog(this, "Data gagal ditambahkan, " + "karena no telepon " + txtTelepon.getText() + " telah digunakan", "Informasi", JOptionPane.ERROR_MESSAGE);
                    return;
                } else {
                    try {

                        perintah.execute("INSERT INTO anggota VALUES('"
                                + txtID.getText() + "','"
                                + txtNama.getText() + "','"
                                + txtEmail.getText() + "','"
                                + txtTelepon.getText() + "','"
                                + cbxJenisKelamin.getSelectedItem() + "','"
                                + txtTanggal.getText() + "')"
                        );
                        JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                        tampilData();
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Informasi", JOptionPane.ERROR_MESSAGE);
                        e.printStackTrace();

                    }
                }
            } else { // mode update
                if ((tblData.getSelectedRow() == -1) && (dataDitemukan == false)) {
                    JOptionPane.showMessageDialog(this, "Silahkan pilih baris yang akan diubah!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                } else if (emailDitemukan) {
                    JOptionPane.showMessageDialog(this, "Data gagal diupdate, " + "karena email " + txtEmail.getText() + " telah digunakan", "Informasi", JOptionPane.ERROR_MESSAGE);
                    return;
                } else if (teleponDitemukan) {
                    JOptionPane.showMessageDialog(this, "Data gagal diupdate, " + "karena no telepon " + txtTelepon.getText() + " telah digunakan", "Informasi", JOptionPane.ERROR_MESSAGE);
                    return;
                } else {
                    try {
                        perintah.execute("UPDATE anggota SET "
                                + "nama_anggota = '" + txtNama.getText() + "', "
                                + "email = '" + txtEmail.getText() + "', "
                                + "telepon = '" + txtTelepon.getText() + "', "
                                + "jenis_kelamin = '" + cbxJenisKelamin.getSelectedItem() + "', "
                                + "tgl_join = '" + txtTanggal.getText() + "' "
                                + "WHERE kode_anggota = '" + txtID.getText() + "'");
                        JOptionPane.showMessageDialog(this, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                        tampilData();
                    } catch (SQLException e) {
                        System.err.println("Query Error");
                        e.printStackTrace();

                    }
                }
            }

            bersihData();
            txtID.setEnabled(false);
            txtNama.setEnabled(false);
            txtEmail.setEnabled(false);
            txtTelepon.setEnabled(false);
            cbxJenisKelamin.setEnabled(false);
            txtTanggal.setEnabled(false);
            btnBaru.requestFocus();
            btnBaru.setEnabled(true);
            btnSimpan.setEnabled(false);
            btnUbah.setEnabled(false);
            btnHapus.setEnabled(false);
            btnBatal.setEnabled(false);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        txtSearch.setText("");
    }//GEN-LAST:event_txtSearchMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        bersihData();
        tampilData();
        txtID.setEnabled(false);
        txtNama.setEnabled(false);
        txtEmail.setEnabled(false);
        txtTelepon.setEnabled(false);
        cbxJenisKelamin.setEnabled(false);
        txtTanggal.setEnabled(false);
        btnBaru.setEnabled(true);
        btnBaru.requestFocus();
        btnSimpan.setEnabled(false);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        if (txtID.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Silahkan isi kode anggota terlebih dahulu!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            txtID.requestFocus();
            return;
            }
            dataDitemukan = cariData(txtID.getText());
            if (dataDitemukan == true) {
                int pilihan;
                pilihan = JOptionPane.showConfirmDialog(this, "Kode Anggota " + txtID.getText() + " sudah ada! " + "Apakah anda ingin mengubah/menghapus data ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (pilihan == 0) {
                    try {
                        txtNama.setText(rs.getString("nama_anggota"));
                        txtEmail.setText(rs.getString("email"));
                        txtTelepon.setText(rs.getString("telepon"));
                        cbxJenisKelamin.setSelectedItem(rs.getString("jenis_kelamin"));
                        txtTanggal.setText(rs.getString("tgl_join"));
                        txtID.setEnabled(false);
                        txtNama.setEnabled(false);
                        txtEmail.setEnabled(false);
                        txtTelepon.setEnabled(false);
                        btnBaru.setEnabled(false);
                        btnSimpan.setEnabled(false);
                        btnHapus.setEnabled(false);
                        btnUbah.requestFocus();
                        btnUbah.setEnabled(true);
                        btnBatal.setEnabled(true);
                    } catch (SQLException e) {
                        System.err.println("Query Error");
                        e.printStackTrace();
                    }
                } else {
                    txtID.setText("");
                    txtID.requestFocus();
                }
            } else {
                txtID.setEnabled(false);
                txtNama.setEnabled(true);
                txtEmail.setEnabled(true);
                txtTelepon.setEnabled(true);
                cbxJenisKelamin.setEnabled(true);
                txtNama.requestFocus();
                txtTanggal.setEnabled(true);
                btnSimpan.setEnabled(true);
                btnBatal.setEnabled(true);
            }
        }
    }//GEN-LAST:event_txtIDKeyReleased

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        bersihData();
        txtID.setEnabled(true);
        txtID.requestFocus();
        txtNama.setEnabled(false);
        txtEmail.setEnabled(false);
        txtTelepon.setEnabled(false);
        cbxJenisKelamin.setEnabled(false);
        txtTanggal.setEnabled(false);
        btnSimpan.setEnabled(false);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBaru.setEnabled(false);
        btnBatal.setEnabled(true);
        modeSimpan = true;
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        bersihData();
        txtID.setEnabled(false);
        txtNama.setEnabled(false);
        txtEmail.setEnabled(false);
        txtTelepon.setEnabled(false);
        cbxJenisKelamin.setEnabled(false);
        txtTanggal.setEnabled(false);
        btnBaru.requestFocus();
        btnBaru.setEnabled(true);
        btnSimpan.setEnabled(false);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);

    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isLetter(c) || c == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNamaKeyTyped

    private void txtTeleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeleponKeyTyped
        char c = evt.getKeyChar();

        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
        if (txtTelepon.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTeleponKeyTyped

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        if (tblData.getSelectedRow() >= 0) {
            txtID.setText(model.getValueAt(tblData.getSelectedRow(), 0).toString());
            txtNama.setText(model.getValueAt(tblData.getSelectedRow(), 1).toString());
            txtEmail.setText(model.getValueAt(tblData.getSelectedRow(), 2).toString());
            txtTelepon.setText(model.getValueAt(tblData.getSelectedRow(), 3).toString());
            cbxJenisKelamin.setSelectedItem(model.getValueAt(tblData.getSelectedRow(), 4).toString());
            txtTanggal.setText(model.getValueAt(tblData.getSelectedRow(), 5).toString());

            btnBaru.setEnabled(false);
            btnSimpan.setEnabled(false);
            btnUbah.setEnabled(true);
            btnHapus.setEnabled(true);
            btnUbah.requestFocus();
            btnBatal.setEnabled(true);
        }
    }//GEN-LAST:event_tblDataMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        txtID.setEnabled(false);
        txtNama.setEnabled(true);
        txtEmail.setEnabled(true);
        txtTelepon.setEnabled(true);
        txtTanggal.setEnabled(true);
        cbxJenisKelamin.setEnabled(true);
        txtNama.requestFocus();
        btnBaru.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(true);

        modeSimpan = false;
    }//GEN-LAST:event_btnUbahActionPerformed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        if (txtID.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        if (txtEmail.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        if ((tblData.getSelectedRow() == -1) && (dataDitemukan == false)) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih baris data yang akan dihapus!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int pilihan;
            pilihan = JOptionPane.showConfirmDialog(this, "Apakah anda yakin akan menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (pilihan == 0) {
                try {
                    perintah.execute("DELETE FROM anggota " + "WHERE kode_anggota = '" + txtID.getText() + "'");
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    tampilData();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus karena terhubung dengan data lain", "Informasi", JOptionPane.ERROR_MESSAGE);
                }
                bersihData();
                btnBaru.requestFocus();
                btnBaru.setEnabled(true);
                btnSimpan.setEnabled(false);
                btnUbah.setEnabled(false);
                btnHapus.setEnabled(false);
                btnBatal.setEnabled(false);

            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        String keyword = txtSearch.getText();

        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        model.setRowCount(0);
        try {
            String sql = "SELECT * FROM anggota WHERE kode_anggota LIKE ? OR nama_anggota LIKE ? OR email LIKE ? OR telepon LIKE ? OR jenis_kelamin LIKE ? OR tgl_join LIKE ?";
            try (PreparedStatement st = koneksi.prepareStatement(sql)) {
                st.setString(1, "%" + keyword + "%");
                st.setString(2, "%" + keyword + "%");
                st.setString(3, "%" + keyword + "%");
                st.setString(4, "%" + keyword + "%");
                st.setString(5, "%" + keyword + "%");
                st.setString(6, "%" + keyword + "%");
                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("kode_anggota"),
                        rs.getString("nama_anggota"),
                        rs.getString("email"),
                        rs.getString("telepon"),
                        rs.getString("jenis_kelamin"),
                        rs.getString("tgl_join")
                    });
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtSearchKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbxJenisKelamin;
    private com.raven.datechooser.DateChooser dateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables

    private void bersihData() {
        txtID.setText("");
        txtNama.setText("");
        txtEmail.setText("");
        txtTelepon.setText("");
        cbxJenisKelamin.setSelectedIndex(-1);
        txtTanggal.setText("");
    }

    private void tampilData() {
        try {
            rs = perintah.executeQuery("SELECT * FROM anggota");
            model.setRowCount(0);
            model.fireTableDataChanged();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("kode_anggota"),
                    rs.getString("nama_anggota"),
                    rs.getString("email"),
                    rs.getString("telepon"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("tgl_join")
                });
            }
        } catch (SQLException e) {
            System.err.println("Query Error");
            e.printStackTrace();
        }
    }

    private boolean cariData(String data) {
        if (!txtID.getText().equals("")) {
            try {
                rs = perintah.executeQuery("SELECT * FROM anggota "
                        + "WHERE kode_anggota = '" + data + "'");

                if (rs.next()) {
                    return true;
                } else {
                    return false;
                }
            } catch (SQLException e) {
                System.err.println("Query Error");
                e.printStackTrace();
            }
        }
        return false;
    }

    private boolean cariDataEmail(String data) {
        if (!txtEmail.getText().equals("")) {
            try {
                rs = perintah.executeQuery("SELECT * FROM anggota WHERE kode_anggota!='" + txtID.getText() + "' AND email LIKE BINARY '" + txtEmail.getText() + "'");

                if (rs.next()) {
                    return true;
                } else {
                    return false;
                }
            } catch (SQLException e) {
                System.err.println("Query Error");
                e.printStackTrace();
            }
        }
        return false;
    }

    private boolean cariDataTelepon(String data) {
        if (!txtTelepon.getText().equals("")) {
            try {
                rs = perintah.executeQuery("SELECT * FROM anggota WHERE kode_anggota!='" + txtID.getText() + "' AND telepon LIKE BINARY '" + txtTelepon.getText() + "'");

                if (rs.next()) {
                    return true;
                } else {
                    return false;
                }
            } catch (SQLException e) {
                System.err.println("Query Error");
                e.printStackTrace();
            }
        }
        return false;
    }

}
