/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import java.awt.Color;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.awt.Desktop;
import java.awt.Dialog;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author Doni Fitriansyah
 */
public class MainMenu extends javax.swing.JFrame {

    public String kodeUser() {
        return kodeUser;
    }

    public String getrole() {
        return role;
    }

    public String getNamaUser() {
        return namaUser;
    }

    public String getUserName() {
        return userName;
    }

    private String kodeUser;
    private String role;
    private String namaUser;
    private String userName;
    private String passwordUser;
    Connection koneksi;
    Statement perintah;
    DefaultTableModel model;
    ResultSet rs;
    MenuLogin login;

    public MainMenu(String kodeUser, String role, String namaUser, String userName, String passwordUser) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost/sipustaka";
            String user = "root";
            String password = "";
            koneksi = DriverManager.getConnection(url, user, password);
            perintah = koneksi.createStatement();

        } catch (ClassNotFoundException e) {
            System.err.println("JDBC Driver tidak ditemukan");
        } catch (SQLException e) {
            System.err.println("Gagal koneksi atau menciptakan objek statement");
        }
        this.kodeUser = kodeUser;
        this.role = role;
        this.userName = userName;
        this.namaUser = namaUser;
        this.passwordUser = passwordUser;

        initComponents();
        model = (DefaultTableModel) tblData.getModel();
        tampilData();
        setWaktu();
        DataTotal();
        setExtendedState(MAXIMIZED_BOTH);
        labelNamaUser.setText(namaUser);
        labelUsername.setText(userName);
        if (role.equals("petugas")) {
            sideBar.remove(Petugas);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sideBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Anggota = new javax.swing.JPanel();
        labelAnggota = new javax.swing.JLabel();
        iconAnggota = new javax.swing.JLabel();
        Buku = new javax.swing.JPanel();
        labelBuku = new javax.swing.JLabel();
        iconBuku = new javax.swing.JLabel();
        Kategori = new javax.swing.JPanel();
        labelKategori = new javax.swing.JLabel();
        iconKategori = new javax.swing.JLabel();
        Penerbit = new javax.swing.JPanel();
        labelPenerbit = new javax.swing.JLabel();
        iconPenerbit = new javax.swing.JLabel();
        Petugas = new javax.swing.JPanel();
        labelPetugas = new javax.swing.JLabel();
        iconPetugas = new javax.swing.JLabel();
        Peminjaman = new javax.swing.JPanel();
        labelPeminjaman = new javax.swing.JLabel();
        iconPeminjaman = new javax.swing.JLabel();
        Pengembalian = new javax.swing.JPanel();
        labelPengembalian = new javax.swing.JLabel();
        iconPengembalian = new javax.swing.JLabel();
        Laporan = new javax.swing.JPanel();
        labelLaporan = new javax.swing.JLabel();
        iconLaporan = new javax.swing.JLabel();
        User = new javax.swing.JPanel();
        iconUser = new javax.swing.JLabel();
        labelNamaUser = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelWaktu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelMain = new javax.swing.JPanel();
        cardBuku = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBuku = new javax.swing.JLabel();
        cardAnggota = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblAnggota = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cardPengembalian = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPengembalian = new javax.swing.JLabel();
        cardPeminjaman = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPeminjaman = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        lblReferensi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        sideBar.setBackground(new java.awt.Color(255, 204, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/iconSipustaka.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SiPustaka");

        Anggota.setBackground(new java.awt.Color(255, 204, 0));

        labelAnggota.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        labelAnggota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAnggota.setText("Data Anggota");
        labelAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAnggotaMouseClicked(evt);
            }
        });

        iconAnggota.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        iconAnggota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Sidebar/anggota.png"))); // NOI18N
        iconAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAnggotaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AnggotaLayout = new javax.swing.GroupLayout(Anggota);
        Anggota.setLayout(AnggotaLayout);
        AnggotaLayout.setHorizontalGroup(
            AnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconAnggota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AnggotaLayout.setVerticalGroup(
            AnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnggotaLayout.createSequentialGroup()
                .addComponent(iconAnggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Buku.setBackground(new java.awt.Color(255, 204, 0));

        labelBuku.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        labelBuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuku.setText("Data Buku");
        labelBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBukuMouseClicked(evt);
            }
        });

        iconBuku.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        iconBuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Sidebar/buku.png"))); // NOI18N
        iconBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconBukuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BukuLayout = new javax.swing.GroupLayout(Buku);
        Buku.setLayout(BukuLayout);
        BukuLayout.setHorizontalGroup(
            BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconBuku, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BukuLayout.setVerticalGroup(
            BukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BukuLayout.createSequentialGroup()
                .addComponent(iconBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Kategori.setBackground(new java.awt.Color(255, 204, 0));

        labelKategori.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        labelKategori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelKategori.setText("Data Kategori");
        labelKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelKategoriMouseClicked(evt);
            }
        });

        iconKategori.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        iconKategori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Sidebar/kategori.png"))); // NOI18N
        iconKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconKategoriMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout KategoriLayout = new javax.swing.GroupLayout(Kategori);
        Kategori.setLayout(KategoriLayout);
        KategoriLayout.setHorizontalGroup(
            KategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconKategori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        KategoriLayout.setVerticalGroup(
            KategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KategoriLayout.createSequentialGroup()
                .addComponent(iconKategori)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Penerbit.setBackground(new java.awt.Color(255, 204, 0));

        labelPenerbit.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        labelPenerbit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPenerbit.setText("Data Penerbit");
        labelPenerbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPenerbitMouseClicked(evt);
            }
        });

        iconPenerbit.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        iconPenerbit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPenerbit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Sidebar/publisher.png"))); // NOI18N
        iconPenerbit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPenerbitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PenerbitLayout = new javax.swing.GroupLayout(Penerbit);
        Penerbit.setLayout(PenerbitLayout);
        PenerbitLayout.setHorizontalGroup(
            PenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iconPenerbit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PenerbitLayout.setVerticalGroup(
            PenerbitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PenerbitLayout.createSequentialGroup()
                .addComponent(iconPenerbit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Petugas.setBackground(new java.awt.Color(255, 204, 0));

        labelPetugas.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        labelPetugas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPetugas.setText("Data Petugas");
        labelPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPetugasMouseClicked(evt);
            }
        });

        iconPetugas.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        iconPetugas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Sidebar/petugas.png"))); // NOI18N
        iconPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPetugasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PetugasLayout = new javax.swing.GroupLayout(Petugas);
        Petugas.setLayout(PetugasLayout);
        PetugasLayout.setHorizontalGroup(
            PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iconPetugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PetugasLayout.setVerticalGroup(
            PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PetugasLayout.createSequentialGroup()
                .addComponent(iconPetugas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Peminjaman.setBackground(new java.awt.Color(255, 204, 0));

        labelPeminjaman.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        labelPeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPeminjaman.setText("Peminjaman");
        labelPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPeminjamanMouseClicked(evt);
            }
        });

        iconPeminjaman.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        iconPeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Sidebar/peminjaman.png"))); // NOI18N
        iconPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPeminjamanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PeminjamanLayout = new javax.swing.GroupLayout(Peminjaman);
        Peminjaman.setLayout(PeminjamanLayout);
        PeminjamanLayout.setHorizontalGroup(
            PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iconPeminjaman, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PeminjamanLayout.setVerticalGroup(
            PeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeminjamanLayout.createSequentialGroup()
                .addComponent(iconPeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Pengembalian.setBackground(new java.awt.Color(255, 204, 0));

        labelPengembalian.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        labelPengembalian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPengembalian.setText("Pengembalian");
        labelPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPengembalianMouseClicked(evt);
            }
        });

        iconPengembalian.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        iconPengembalian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Sidebar/pengembalian.png"))); // NOI18N
        iconPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconPengembalianMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PengembalianLayout = new javax.swing.GroupLayout(Pengembalian);
        Pengembalian.setLayout(PengembalianLayout);
        PengembalianLayout.setHorizontalGroup(
            PengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(iconPengembalian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PengembalianLayout.setVerticalGroup(
            PengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PengembalianLayout.createSequentialGroup()
                .addComponent(iconPengembalian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Laporan.setBackground(new java.awt.Color(255, 204, 0));

        labelLaporan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        labelLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLaporan.setText("Laporan Pengembalian");
        labelLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLaporanMouseClicked(evt);
            }
        });

        iconLaporan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        iconLaporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Sidebar/laporan.png"))); // NOI18N
        iconLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconLaporanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LaporanLayout = new javax.swing.GroupLayout(Laporan);
        Laporan.setLayout(LaporanLayout);
        LaporanLayout.setHorizontalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
            .addComponent(iconLaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LaporanLayout.setVerticalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LaporanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        User.setBackground(new java.awt.Color(255, 204, 0));

        iconUser.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        iconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Sidebar/user.png"))); // NOI18N
        iconUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconUserMouseClicked(evt);
            }
        });

        labelNamaUser.setFont(new java.awt.Font("Poppins Medium", 0, 10)); // NOI18N
        labelNamaUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNamaUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNamaUserMouseClicked(evt);
            }
        });

        labelUsername.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUsernameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout UserLayout = new javax.swing.GroupLayout(User);
        User.setLayout(UserLayout);
        UserLayout.setHorizontalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelNamaUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UserLayout.setVerticalGroup(
            UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNamaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        labelWaktu.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        labelWaktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Anggota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Buku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Penerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Kategori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Petugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Peminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Pengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelWaktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Peminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(labelWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("-");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cardBuku.setBackground(new java.awt.Color(255, 204, 0));

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BUKU");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/book-card.png"))); // NOI18N

        lblBuku.setFont(new java.awt.Font("Poppins Medium", 0, 48)); // NOI18N
        lblBuku.setForeground(new java.awt.Color(255, 255, 255));
        lblBuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout cardBukuLayout = new javax.swing.GroupLayout(cardBuku);
        cardBuku.setLayout(cardBukuLayout);
        cardBukuLayout.setHorizontalGroup(
            cardBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBukuLayout.createSequentialGroup()
                .addGroup(cardBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardBukuLayout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardBukuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardBukuLayout.setVerticalGroup(
            cardBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        cardAnggota.setBackground(new java.awt.Color(255, 204, 0));

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ANGGOTA");

        lblAnggota.setFont(new java.awt.Font("Poppins Medium", 0, 48)); // NOI18N
        lblAnggota.setForeground(new java.awt.Color(255, 255, 255));
        lblAnggota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/anggota.png"))); // NOI18N

        javax.swing.GroupLayout cardAnggotaLayout = new javax.swing.GroupLayout(cardAnggota);
        cardAnggota.setLayout(cardAnggotaLayout);
        cardAnggotaLayout.setHorizontalGroup(
            cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addGroup(cardAnggotaLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cardAnggotaLayout.setVerticalGroup(
            cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel14.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel14.setText("Riwayat Peminjaman Buku");

        cardPengembalian.setBackground(new java.awt.Color(255, 204, 0));

        jLabel10.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SUDAH DIKEMBALIKAN");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/in.png"))); // NOI18N

        lblPengembalian.setFont(new java.awt.Font("Poppins Medium", 0, 48)); // NOI18N
        lblPengembalian.setForeground(new java.awt.Color(255, 255, 255));
        lblPengembalian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout cardPengembalianLayout = new javax.swing.GroupLayout(cardPengembalian);
        cardPengembalian.setLayout(cardPengembalianLayout);
        cardPengembalianLayout.setHorizontalGroup(
            cardPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPengembalianLayout.createSequentialGroup()
                .addGroup(cardPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cardPengembalianLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cardPengembalianLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        cardPengembalianLayout.setVerticalGroup(
            cardPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPengembalianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardPeminjaman.setBackground(new java.awt.Color(255, 204, 0));

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SEDANG DIPINJAM");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/out.png"))); // NOI18N

        lblPeminjaman.setFont(new java.awt.Font("Poppins Medium", 0, 48)); // NOI18N
        lblPeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        lblPeminjaman.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout cardPeminjamanLayout = new javax.swing.GroupLayout(cardPeminjaman);
        cardPeminjaman.setLayout(cardPeminjamanLayout);
        cardPeminjamanLayout.setHorizontalGroup(
            cardPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardPeminjamanLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addContainerGap())
        );
        cardPeminjamanLayout.setVerticalGroup(
            cardPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Peminjaman", "Peminjaman", "Pengembalian", "Kode Anggota (NIM)", "Nama Anggota", "Kode Buku", "Judul Buku", "Pengarang", "Jumlah Pinjam", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblData);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addComponent(cardAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cardBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cardPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cardPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 284, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardAnggota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardPengembalian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        jButton3.setText("Logout");
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblReferensi.setForeground(new java.awt.Color(0, 0, 204));
        lblReferensi.setText("Referensi");
        lblReferensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReferensiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblReferensi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(lblReferensi))
                .addGap(10, 10, 10)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAnggotaMouseClicked
        // TODO add your handling code here:
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PetugasNonAktif();
        PengembalianNonAktif();
        PeminjamanNonAktif();
        LaporanNonAktif();
        AnggotaAktif();
        AnggotaOpen();
    }//GEN-LAST:event_labelAnggotaMouseClicked

    private void iconAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAnggotaMouseClicked
        // TODO add your handling code here:
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PetugasNonAktif();
        PengembalianNonAktif();
        PeminjamanNonAktif();
        LaporanNonAktif();
        AnggotaAktif();
        AnggotaOpen();
    }//GEN-LAST:event_iconAnggotaMouseClicked

    private void labelBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBukuMouseClicked
        AnggotaNonAktif();
        UserNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PetugasNonAktif();
        PengembalianNonAktif();
        PeminjamanNonAktif();
        LaporanNonAktif();
        BukuAktif();
        BukuOpen();
    }//GEN-LAST:event_labelBukuMouseClicked

    private void iconBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconBukuMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PetugasNonAktif();
        PengembalianNonAktif();
        PeminjamanNonAktif();
        LaporanNonAktif();
        BukuAktif();
        BukuOpen();

    }//GEN-LAST:event_iconBukuMouseClicked

    private void labelKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelKategoriMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        BukuNonAktif();
        PenerbitNonAktif();
        PetugasNonAktif();
        PengembalianNonAktif();
        PeminjamanNonAktif();
        LaporanNonAktif();
        KategoriAktif();
        KategoriOpen();
    }//GEN-LAST:event_labelKategoriMouseClicked

    private void iconKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconKategoriMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        BukuNonAktif();
        PenerbitNonAktif();
        PetugasNonAktif();
        PengembalianNonAktif();
        PeminjamanNonAktif();
        LaporanNonAktif();
        KategoriAktif();
        KategoriOpen();

    }//GEN-LAST:event_iconKategoriMouseClicked

    private void labelPenerbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPenerbitMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PetugasNonAktif();
        PengembalianNonAktif();
        PeminjamanNonAktif();
        LaporanNonAktif();
        PenerbitAktif();
        PenerbitOpen();
    }//GEN-LAST:event_labelPenerbitMouseClicked

    private void iconPenerbitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPenerbitMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PetugasNonAktif();
        PengembalianNonAktif();
        PeminjamanNonAktif();
        LaporanNonAktif();
        PenerbitAktif();
        PenerbitOpen();
    }//GEN-LAST:event_iconPenerbitMouseClicked

    private void labelPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPetugasMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PengembalianNonAktif();
        PeminjamanNonAktif();
        LaporanNonAktif();
        PetugasAktif();
        PetugasOpen();
    }//GEN-LAST:event_labelPetugasMouseClicked

    private void iconPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPetugasMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PengembalianNonAktif();
        PeminjamanNonAktif();
        LaporanNonAktif();
        PetugasAktif();
        PetugasOpen();
    }//GEN-LAST:event_iconPetugasMouseClicked

    private void labelPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPeminjamanMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PengembalianNonAktif();
        LaporanNonAktif();
        PetugasNonAktif();
        PeminjamanAktif();
        PeminjamanOpen();
    }//GEN-LAST:event_labelPeminjamanMouseClicked

    private void iconPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPeminjamanMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PengembalianNonAktif();
        LaporanNonAktif();
        PetugasNonAktif();
        PeminjamanAktif();
        PeminjamanOpen();

    }//GEN-LAST:event_iconPeminjamanMouseClicked

    private void labelPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPengembalianMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        LaporanNonAktif();
        PetugasNonAktif();
        PeminjamanNonAktif();
        PengembalianAktif();
        PengembalianOpen();
    }//GEN-LAST:event_labelPengembalianMouseClicked

    private void iconPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconPengembalianMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        LaporanNonAktif();
        PetugasNonAktif();
        PeminjamanNonAktif();
        PengembalianAktif();
        PengembalianOpen();
    }//GEN-LAST:event_iconPengembalianMouseClicked

    private void labelLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLaporanMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PetugasNonAktif();
        PeminjamanNonAktif();
        PengembalianNonAktif();
        LaporanAktif();
        LaporanPeminjamanOpen();
    }//GEN-LAST:event_labelLaporanMouseClicked

    private void iconLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconLaporanMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        UserNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PetugasNonAktif();
        PeminjamanNonAktif();
        PengembalianNonAktif();
        LaporanAktif();
        LaporanPeminjamanOpen();
    }//GEN-LAST:event_iconLaporanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void labelUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUsernameMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PetugasNonAktif();
        PeminjamanNonAktif();
        PengembalianNonAktif();
        LaporanNonAktif();
        UserAktif();
        UserOpen();
    }//GEN-LAST:event_labelUsernameMouseClicked

    private void iconUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconUserMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PetugasNonAktif();
        PeminjamanNonAktif();
        PengembalianNonAktif();
        LaporanNonAktif();
        UserAktif();
        UserOpen();
    }//GEN-LAST:event_iconUserMouseClicked

    private void labelNamaUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNamaUserMouseClicked
        // TODO add your handling code here:
        AnggotaNonAktif();
        BukuNonAktif();
        KategoriNonAktif();
        PenerbitNonAktif();
        PetugasNonAktif();
        PeminjamanNonAktif();
        PengembalianNonAktif();
        LaporanNonAktif();
        UserNonAktif();
        UserOpen();
    }//GEN-LAST:event_labelNamaUserMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int pilihan;
        pilihan = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (pilihan == 0) {
            dispose();
            MenuLogin login = new MenuLogin();
            login.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lblReferensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReferensiMouseClicked
        try {
            String path = "src/Laporan/Referensi.pdf";
            Desktop desktop = Desktop.getDesktop();
            desktop.open(new File(path));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblReferensiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Anggota;
    private javax.swing.JPanel Buku;
    private javax.swing.JPanel Kategori;
    private javax.swing.JPanel Laporan;
    private javax.swing.JPanel Peminjaman;
    private javax.swing.JPanel Penerbit;
    private javax.swing.JPanel Pengembalian;
    private javax.swing.JPanel Petugas;
    private javax.swing.JPanel User;
    private javax.swing.JPanel cardAnggota;
    private javax.swing.JPanel cardBuku;
    private javax.swing.JPanel cardPeminjaman;
    private javax.swing.JPanel cardPengembalian;
    private javax.swing.JLabel iconAnggota;
    private javax.swing.JLabel iconBuku;
    private javax.swing.JLabel iconKategori;
    private javax.swing.JLabel iconLaporan;
    private javax.swing.JLabel iconPeminjaman;
    private javax.swing.JLabel iconPenerbit;
    private javax.swing.JLabel iconPengembalian;
    private javax.swing.JLabel iconPetugas;
    private javax.swing.JLabel iconUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAnggota;
    private javax.swing.JLabel labelBuku;
    private javax.swing.JLabel labelKategori;
    private javax.swing.JLabel labelLaporan;
    private javax.swing.JLabel labelNamaUser;
    private javax.swing.JLabel labelPeminjaman;
    private javax.swing.JLabel labelPenerbit;
    private javax.swing.JLabel labelPengembalian;
    private javax.swing.JLabel labelPetugas;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelWaktu;
    private javax.swing.JLabel lblAnggota;
    private javax.swing.JLabel lblBuku;
    private javax.swing.JLabel lblPeminjaman;
    private javax.swing.JLabel lblPengembalian;
    private javax.swing.JLabel lblReferensi;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel sideBar;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables

    private void AnggotaAktif() {

        labelAnggota.setForeground(Color.white);
        iconAnggota.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/anggota-hover.png")));
    }

    private void AnggotaNonAktif() {

        labelAnggota.setForeground(Color.black);
        iconAnggota.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/anggota.png")));
    }

    private void BukuAktif() {
        labelBuku.setForeground(Color.white);
        iconBuku.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/buku-hover.png")));
    }

    private void BukuNonAktif() {

        labelBuku.setForeground(Color.black);
        iconBuku.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/buku.png")));
    }

    private void KategoriAktif() {

        labelKategori.setForeground(Color.white);
        iconKategori.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/kategori-hover.png")));
    }

    private void KategoriNonAktif() {

        labelKategori.setForeground(Color.black);
        iconKategori.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/kategori.png")));
    }

    private void PenerbitAktif() {

        labelPenerbit.setForeground(Color.white);
        iconPenerbit.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/publisher-hover.png")));
    }

    private void PenerbitNonAktif() {

        labelPenerbit.setForeground(Color.black);
        iconPenerbit.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/publisher.png")));
    }

    private void PetugasAktif() {

        labelPetugas.setForeground(Color.white);
        iconPetugas.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/petugas-hover.png")));
    }

    private void PetugasNonAktif() {

        labelPetugas.setForeground(Color.black);
        iconPetugas.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/petugas.png")));
    }

    private void PeminjamanAktif() {

        labelPeminjaman.setForeground(Color.white);
        iconPeminjaman.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/peminjaman-hover.png")));
    }

    private void PeminjamanNonAktif() {

        labelPeminjaman.setForeground(Color.black);
        iconPeminjaman.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/peminjaman.png")));
    }

    private void PengembalianAktif() {

        labelPengembalian.setForeground(Color.white);
        iconPengembalian.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/pengembalian-hover.png")));
    }

    private void PengembalianNonAktif() {

        labelPengembalian.setForeground(Color.black);
        iconPengembalian.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/pengembalian.png")));
    }

    private void LaporanAktif() {

        labelLaporan.setForeground(Color.white);
        iconLaporan.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/laporan-hover.png")));
    }

    private void LaporanNonAktif() {

        labelLaporan.setForeground(Color.black);
        iconLaporan.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/laporan.png")));
    }

    private void UserAktif() {

        labelUsername.setForeground(Color.white);
        labelNamaUser.setForeground(Color.white);
        iconUser.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/user-hover.png")));
    }

    private void UserNonAktif() {

        labelUsername.setForeground(Color.black);
        labelNamaUser.setForeground(Color.black);
        iconUser.setIcon(new ImageIcon(getClass().getResource("../gambar/sidebar/user.png")));
    }

    private void setWaktu() {
        Timer timer = new Timer(0, e -> {
            Calendar calendar = Calendar.getInstance();
            SimpleDateFormat formatHari = new SimpleDateFormat("EEEE", new Locale("in", "ID"));
            SimpleDateFormat formatTgl = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");

            labelWaktu.setText(formatHari.format(calendar.getTime()) + ", " + formatTgl.format(new Date()));
        });

        timer.start();
    }

    private void AnggotaOpen() {

        panelMain.setVisible(false);
        KelolaDataAnggota menu = new KelolaDataAnggota(this, true);
        menu.setLocationRelativeTo(menu);
        menu.setVisible(true);
        menu.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                AnggotaNonAktif();
                DataTotal();
                panelMain.setVisible(true);
            }
        });
    }

    private void PenerbitOpen() {
        panelMain.setVisible(false);
        KelolaDataPenerbit menu = new KelolaDataPenerbit(this, true);
        menu.setLocationRelativeTo(menu);
        menu.setVisible(true);
        menu.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                PenerbitNonAktif();
                DataTotal();
                panelMain.setVisible(true);
            }
        });
    }

    private void KategoriOpen() {
        panelMain.setVisible(false);
        KelolaDataKategori menu = new KelolaDataKategori(this, true);
        menu.setLocationRelativeTo(menu);
        menu.setVisible(true);
        menu.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                KategoriNonAktif();
                DataTotal();
                panelMain.setVisible(true);
            }
        });
    }

    private void BukuOpen() {
        panelMain.setVisible(false);
        KelolaDataBuku menu = new KelolaDataBuku(this, true);
        menu.setLocationRelativeTo(menu);
        menu.setVisible(true);
        menu.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                BukuNonAktif();
                DataTotal();
                panelMain.setVisible(true);
            }
        });
    }

    private void PetugasOpen() {
        panelMain.setVisible(false);
        KelolaDataPetugas menu = new KelolaDataPetugas(this, true);
        menu.setLocationRelativeTo(menu);
        menu.setVisible(true);
        menu.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                DataTotal();
                PetugasNonAktif();
                panelMain.setVisible(true);
            }
        });
    }

    private void PeminjamanOpen() {
        panelMain.setVisible(false);
        PeminjamanBuku menu = new PeminjamanBuku(this, true, kodeUser);
        menu.setLocationRelativeTo(menu);
        menu.setVisible(true);
        menu.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                PeminjamanNonAktif();
                tampilData();
                DataTotal();
                panelMain.setVisible(true);

            }
        });
    }

    private void PengembalianOpen() {
        panelMain.setVisible(false);
        PengembalianBuku menu = new PengembalianBuku(this, true, kodeUser);
        menu.setLocationRelativeTo(menu);
        menu.setVisible(true);
        menu.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                PengembalianNonAktif();
                tampilData();
                DataTotal();
                panelMain.setVisible(true);
            }
        });
    }

    private void UserOpen() {
        panelMain.setVisible(false);
        UbahDataPetugas menu = new UbahDataPetugas(this, true, kodeUser, namaUser, userName, passwordUser);
        menu.setLocationRelativeTo(menu);
        menu.setVisible(true);
        menu.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                UserNonAktif();
                panelMain.setVisible(true);
            }
        });
    }

    private void LaporanPeminjamanOpen() {
        panelMain.setVisible(false);
        LaporanPeminjaman menu = new LaporanPeminjaman(this, true);
        menu.setLocationRelativeTo(menu);
        menu.setVisible(true);
        menu.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                LaporanNonAktif();
                panelMain.setVisible(true);
            }
        });
    }

    private int jumlahAnggota() {
        int total = 0;
        try {
            String query = "SELECT COUNT(*) AS total FROM anggota";
            PreparedStatement ps = koneksi.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                total = rs.getInt("total");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return total;
    }

    private int jumlahBuku() {
        int total = 0;
        try {
            String query = "SELECT COUNT(*) AS total FROM buku";
            PreparedStatement ps = koneksi.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                total = rs.getInt("total");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return total;
    }
    

    private int jumlahPeminjaman() {
        int total = 0;
        try {
            String query = "SELECT COUNT(*) AS total FROM detail_peminjaman WHERE status_peminjaman = 'Sedang Dipinjam'";
            PreparedStatement ps = koneksi.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                total = rs.getInt("total");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return total;
    }

    private int jumlahPengembalian() {
        int total = 0;
        try {
            String query = "SELECT COUNT(*) AS total FROM detail_peminjaman WHERE status_peminjaman = 'Sudah Dikembalikan'";
            PreparedStatement ps = koneksi.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                total = rs.getInt("total");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return total;
    }

    public void DataTotal() {
        lblAnggota.setText(jumlahAnggota() + "");
        lblBuku.setText(jumlahBuku() + "");
        lblPeminjaman.setText(jumlahPeminjaman() + "");
        lblPengembalian.setText(jumlahPengembalian() + "");
    }

    private void tampilData() {
        try {
            rs = perintah.executeQuery(
                    "SELECT DISTINCT dp.kode_peminjaman, a.nama_anggota, b.judul_buku, b.pengarang, p.tgl_peminjaman, p.tgl_pengembalian, dp.jumlah_pinjam, "
                    + "dp.kode_buku, p.kode_anggota, dp.status_peminjaman "
                    + "FROM detail_peminjaman dp "
                    + "INNER JOIN buku b ON b.kode_buku = dp.kode_buku "
                    + "INNER JOIN peminjaman p ON p.kode_peminjaman = dp.kode_peminjaman "
                    + "INNER JOIN anggota a ON a.kode_anggota = p.kode_anggota "
                    + "ORDER BY dp.status_peminjaman = 'Sedang Dipinjam' ASC, kode_peminjaman ASC; "
            );
            model.setRowCount(0);
            model.fireTableDataChanged();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("kode_peminjaman"),
                    rs.getString("tgl_peminjaman"),
                    rs.getString("tgl_pengembalian"),
                    rs.getString("kode_anggota"),
                    rs.getString("nama_anggota"),
                    rs.getString("kode_buku"),
                    rs.getString("judul_buku"),
                    rs.getString("pengarang"),
                    rs.getString("jumlah_pinjam"),
                    rs.getString("status_peminjaman")
                });
            }
        } catch (SQLException e) {
            System.err.println("Query Error");
            e.printStackTrace();
        }
    }
}
